version: "3.9"
services:
  app:
    hostname: "app"
    build: .
    command: python main.py
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: "postgres"

  postgres:
    hostname: "postgres"
    image: "postgres:13.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
